In [2]:
'55 11 23'.rstrip().split()

['55', '11', '23']

In [3]:
n = int(input().strip())

3 11 23 54 12 85 96 45 23 5


ValueError: invalid literal for int() with base 10: '3 11 23 54 12 85 96 45 23 5'

In [21]:
n=3
arr = []
for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

11 2 4
4 5 6
10 8 -12


In [22]:
arr

[[11, 2, 4], [4, 5, 6], [10, 8, -12]]

In [1]:
import numpy as np

In [24]:

l =np.array(arr)

In [19]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.diagonal(l[:, ::-1])

array([3, 5, 7])

In [15]:
np.abs(sum(np.diagonal(l))-sum(np.diagonal(l[:, ::-1])))

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [25]:
np.abs(sum(np.diagonal(l))-sum(np.diagonal(l[:, ::-1])))

15

In [5]:
n=4
m=3
if (m%2==0) and (n%2 ==0):
    cnt= (m-1)*(n-1)
elif ((m+1)%2==0) and (n%2==0):
    cnt = (m+1)/2 *(n-1)
elif (m%2==0) and ((n+1)%2==0):
    cnt = (n+1)/2 *(m-1)
elif ((m+1)%2==0) and ((n+1)%2==0):
    cnt=(n+1)/2 * (m+1)/2
cnt

6.0

In [ ]:
n=4
m=3
if (m%2==0) and (n%2 ==0):
    cnt= m*n/4
elif ((m+1)%2==0) and (n%2==0):
    cnt = (m-1)*/4+m*n/2
elif (m%2==0) and ((n+1)%2==0):
    cnt = (n+1)/2 *(m-1)
elif ((m+1)%2==0) and ((n+1)%2==0):
    cnt=(n+1)/2 * (m+1)/2
cnt

In [6]:
x1,y1,x2,y2,x3,y3=[0,0,1,1,2,0]

In [39]:
def area(x1, y1, x2, y2, x3, y3): 
  
    return abs((x1 * (y2 - y3) + x2 * (y3 - y1)  
                + x3 * (y1 - y2)) / 2) 
  
def isInside(x1, y1, x2, y2, x3, y3, x, y): 
    A = area (x1, y1, x2, y2, x3, y3) 
    A1 = area (x, y, x2, y2, x3, y3) 
    A2 = area (x1, y1, x, y, x3, y3) 
    A3 = area (x1, y1, x2, y2, x, y) 
    if(A == A1 + A2 + A3): 
        return True
    else: 
        return False

In [4]:
for i in range(5,-5,-1):
    print(i)

In [40]:
for i in range(max(x1,x2,x3),min(x1,x2,x3),-1):
    for j in range(max(y1,y2,y3),min(y1,y2,y3),-1):
        print(i,j)
        if isInside(x1, y1, x2, y2, x3, y3, i, j):
            print([i,j], ' is answer')
        

[1, 1]


In [18]:
l[0:1]

[3, 4, 5, 6, 7]

In [45]:
l =[5,3,4,5,6,7,2,4,6,8,98,2]   

In [61]:
l = list(range(20))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [63]:
random.shuffle(l)
l

[19, 2, 15, 6, 7, 10, 9, 0, 4, 18, 8, 11, 5, 14, 17, 16, 3, 1, 12, 13]

In [46]:

N=14
maxsum = math.inf
for i in range(len(l)):
    sum0=0
    for j in range(i+1, len(l)):
        sum1 = sum(l[i:j])
        if abs(sum1-N)<maxsum:
            print(i , j, sum(l[i:j]))
            maxsum=abs(sum(l[i:j])-N)
            res= (i,j-1)
        else if 
res

SyntaxError: invalid syntax (<ipython-input-46-6c26010ac516>, line 12)

In [54]:
import random
number_list = [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
print ("Original list : ",  number_list)
random.shuffle(number_list) #shuffle method
print ("List after first shuffle  : ",  number_list)

Original list :  [7, 14, 21, 28, 35, 42, 49, 56, 63, 70]
List after first shuffle  :  [14, 7, 28, 35, 63, 49, 70, 21, 42, 56]


In [ ]:
def collinear(x1, y1, x2, y2, x3, y3): 

    a = x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2) 
    if a == 0:
        return True
    else:
        return False

